// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createDraft, editDraft, generateDraft, getDraft, getPost, health, listDrafts, listPosts, login, me, type Options, publishDraft, register } from '../sdk.gen';
import type { CreateDraftData, CreateDraftError, CreateDraftResponse, EditDraftData, EditDraftError, EditDraftResponse, GenerateDraftData, GenerateDraftError, GenerateDraftResponse, GetDraftData, GetDraftError, GetDraftResponse, GetPostData, GetPostError, GetPostResponse, HealthData, ListDraftsData, ListDraftsResponse, ListPostsData, ListPostsResponse, LoginData, LoginError, LoginResponse, MeData, MeResponse, PublishDraftData, PublishDraftError, PublishDraftResponse, RegisterData, RegisterError, RegisterResponse } from '../types.gen';

/**
 * Register
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

export const listDraftsQueryKey = (options?: Options<ListDraftsData>) => createQueryKey('listDrafts', options);

/**
 * List Drafts
 */
export const listDraftsOptions = (options?: Options<ListDraftsData>) => queryOptions<ListDraftsResponse, DefaultError, ListDraftsResponse, ReturnType<typeof listDraftsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDrafts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDraftsQueryKey(options)
});

/**
 * Create Draft
 */
export const createDraftMutation = (options?: Partial<Options<CreateDraftData>>): UseMutationOptions<CreateDraftResponse, CreateDraftError, Options<CreateDraftData>> => {
    const mutationOptions: UseMutationOptions<CreateDraftResponse, CreateDraftError, Options<CreateDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDraftQueryKey = (options: Options<GetDraftData>) => createQueryKey('getDraft', options);

/**
 * Get Draft
 */
export const getDraftOptions = (options: Options<GetDraftData>) => queryOptions<GetDraftResponse, GetDraftError, GetDraftResponse, ReturnType<typeof getDraftQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDraft({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDraftQueryKey(options)
});

/**
 * Edit Draft
 */
export const editDraftMutation = (options?: Partial<Options<EditDraftData>>): UseMutationOptions<EditDraftResponse, EditDraftError, Options<EditDraftData>> => {
    const mutationOptions: UseMutationOptions<EditDraftResponse, EditDraftError, Options<EditDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await editDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Generate Draft
 */
export const generateDraftMutation = (options?: Partial<Options<GenerateDraftData>>): UseMutationOptions<GenerateDraftResponse, GenerateDraftError, Options<GenerateDraftData>> => {
    const mutationOptions: UseMutationOptions<GenerateDraftResponse, GenerateDraftError, Options<GenerateDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Publish Draft
 */
export const publishDraftMutation = (options?: Partial<Options<PublishDraftData>>): UseMutationOptions<PublishDraftResponse, PublishDraftError, Options<PublishDraftData>> => {
    const mutationOptions: UseMutationOptions<PublishDraftResponse, PublishDraftError, Options<PublishDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await publishDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listPostsQueryKey = (options?: Options<ListPostsData>) => createQueryKey('listPosts', options);

/**
 * List Posts
 */
export const listPostsOptions = (options?: Options<ListPostsData>) => queryOptions<ListPostsResponse, DefaultError, ListPostsResponse, ReturnType<typeof listPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listPostsQueryKey(options)
});

export const getPostQueryKey = (options: Options<GetPostData>) => createQueryKey('getPost', options);

/**
 * Get Post
 */
export const getPostOptions = (options: Options<GetPostData>) => queryOptions<GetPostResponse, GetPostError, GetPostResponse, ReturnType<typeof getPostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostQueryKey(options)
});

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});
