// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateDraftData, CreateDraftErrors, CreateDraftResponses, EditDraftData, EditDraftErrors, EditDraftResponses, GenerateDraftData, GenerateDraftErrors, GenerateDraftResponses, GetDraftData, GetDraftErrors, GetDraftResponses, GetPostData, GetPostErrors, GetPostResponses, HealthData, HealthResponses, ListDraftsData, ListDraftsResponses, ListPostsData, ListPostsResponses, LoginData, LoginErrors, LoginResponses, MeData, MeResponses, PublishDraftData, PublishDraftErrors, PublishDraftResponses, RegisterData, RegisterErrors, RegisterResponses, SaveRevisionAsDraftData, SaveRevisionAsDraftErrors, SaveRevisionAsDraftResponses, StreamRevisionData, StreamRevisionErrors, StreamRevisionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * List Drafts
 */
export const listDrafts = <ThrowOnError extends boolean = false>(options?: Options<ListDraftsData, ThrowOnError>): RequestResult<ListDraftsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDraftsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts',
    ...options
});

/**
 * Create Draft
 */
export const createDraft = <ThrowOnError extends boolean = false>(options: Options<CreateDraftData, ThrowOnError>): RequestResult<CreateDraftResponses, CreateDraftErrors, ThrowOnError> => (options.client ?? client).post<CreateDraftResponses, CreateDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Save Revision As Draft
 *
 * Persist the final result of the 'revise my own draft' flow (see
 * POST /api/revisions/stream) as an editable, publishable Draft.
 */
export const saveRevisionAsDraft = <ThrowOnError extends boolean = false>(options: Options<SaveRevisionAsDraftData, ThrowOnError>): RequestResult<SaveRevisionAsDraftResponses, SaveRevisionAsDraftErrors, ThrowOnError> => (options.client ?? client).post<SaveRevisionAsDraftResponses, SaveRevisionAsDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts/from-revision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Draft
 */
export const getDraft = <ThrowOnError extends boolean = false>(options: Options<GetDraftData, ThrowOnError>): RequestResult<GetDraftResponses, GetDraftErrors, ThrowOnError> => (options.client ?? client).get<GetDraftResponses, GetDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts/{draft_id}',
    ...options
});

/**
 * Edit Draft
 */
export const editDraft = <ThrowOnError extends boolean = false>(options: Options<EditDraftData, ThrowOnError>): RequestResult<EditDraftResponses, EditDraftErrors, ThrowOnError> => (options.client ?? client).put<EditDraftResponses, EditDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts/{draft_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Draft
 */
export const generateDraft = <ThrowOnError extends boolean = false>(options: Options<GenerateDraftData, ThrowOnError>): RequestResult<GenerateDraftResponses, GenerateDraftErrors, ThrowOnError> => (options.client ?? client).post<GenerateDraftResponses, GenerateDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts/{draft_id}/generate',
    ...options
});

/**
 * Publish Draft
 */
export const publishDraft = <ThrowOnError extends boolean = false>(options: Options<PublishDraftData, ThrowOnError>): RequestResult<PublishDraftResponses, PublishDraftErrors, ThrowOnError> => (options.client ?? client).post<PublishDraftResponses, PublishDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drafts/{draft_id}/publish',
    ...options
});

/**
 * List Posts
 */
export const listPosts = <ThrowOnError extends boolean = false>(options?: Options<ListPostsData, ThrowOnError>): RequestResult<ListPostsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListPostsResponses, unknown, ThrowOnError>({ url: '/api/posts', ...options });

/**
 * Get Post
 */
export const getPost = <ThrowOnError extends boolean = false>(options: Options<GetPostData, ThrowOnError>): RequestResult<GetPostResponses, GetPostErrors, ThrowOnError> => (options.client ?? client).get<GetPostResponses, GetPostErrors, ThrowOnError>({ url: '/api/posts/{slug}', ...options });

/**
 * Stream Revision
 */
export const streamRevision = <ThrowOnError extends boolean = false>(options: Options<StreamRevisionData, ThrowOnError>): RequestResult<StreamRevisionResponses, StreamRevisionErrors, ThrowOnError> => (options.client ?? client).post<StreamRevisionResponses, StreamRevisionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/revisions/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
