// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DraftCreate
 */
export type DraftCreate = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Audience
     */
    audience?: string;
    /**
     * Tone
     */
    tone?: string;
    /**
     * Key Points
     */
    key_points?: Array<string>;
};

/**
 * DraftEdit
 *
 * Author tweaks to generated content before publishing.
 */
export type DraftEdit = {
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Body Markdown
     */
    body_markdown: string;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * DraftPublic
 */
export type DraftPublic = {
    /**
     * Id
     */
    id: number;
    status: DraftStatus;
    /**
     * Error
     */
    error: string | null;
    /**
     * Topic
     */
    topic: string;
    /**
     * Audience
     */
    audience: string;
    /**
     * Tone
     */
    tone: string;
    /**
     * Key Points
     */
    key_points: Array<string>;
    /**
     * Title
     */
    title: string | null;
    /**
     * Excerpt
     */
    excerpt: string | null;
    /**
     * Body Markdown
     */
    body_markdown: string | null;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DraftSaveFromRevision
 *
 * Persists the final output of the revise flow as an editable Draft.
 */
export type DraftSaveFromRevision = {
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Body Markdown
     */
    body_markdown: string;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * DraftStatus
 *
 * Lifecycle of an AI generation request attached to a draft.
 */
export type DraftStatus = 'pending' | 'generating' | 'ready' | 'failed' | 'published';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PostPublic
 */
export type PostPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Body Markdown
     */
    body_markdown: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes: number;
    /**
     * Published At
     */
    published_at: string;
};

/**
 * PostSummary
 *
 * Listing view — omits the full body to keep payloads small.
 */
export type PostSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes: number;
    /**
     * Published At
     */
    published_at: string;
};

/**
 * RevisionRequest
 *
 * The author's own draft, submitted to be reworked into a 5-minute read.
 *
 * Links are extracted server-side from `draft_text` (they're just pasted
 * inline by the author) rather than supplied as a separate field.
 */
export type RevisionRequest = {
    /**
     * Draft Text
     */
    draft_text: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserPublic;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListDraftsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/drafts';
};

export type ListDraftsResponses = {
    /**
     * Response List Drafts
     *
     * Successful Response
     */
    200: Array<DraftPublic>;
};

export type ListDraftsResponse = ListDraftsResponses[keyof ListDraftsResponses];

export type CreateDraftData = {
    body: DraftCreate;
    path?: never;
    query?: never;
    url: '/api/drafts';
};

export type CreateDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDraftError = CreateDraftErrors[keyof CreateDraftErrors];

export type CreateDraftResponses = {
    /**
     * Successful Response
     */
    201: DraftPublic;
};

export type CreateDraftResponse = CreateDraftResponses[keyof CreateDraftResponses];

export type SaveRevisionAsDraftData = {
    body: DraftSaveFromRevision;
    path?: never;
    query?: never;
    url: '/api/drafts/from-revision';
};

export type SaveRevisionAsDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveRevisionAsDraftError = SaveRevisionAsDraftErrors[keyof SaveRevisionAsDraftErrors];

export type SaveRevisionAsDraftResponses = {
    /**
     * Successful Response
     */
    201: DraftPublic;
};

export type SaveRevisionAsDraftResponse = SaveRevisionAsDraftResponses[keyof SaveRevisionAsDraftResponses];

export type GetDraftData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/drafts/{draft_id}';
};

export type GetDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDraftError = GetDraftErrors[keyof GetDraftErrors];

export type GetDraftResponses = {
    /**
     * Successful Response
     */
    200: DraftPublic;
};

export type GetDraftResponse = GetDraftResponses[keyof GetDraftResponses];

export type EditDraftData = {
    body: DraftEdit;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/drafts/{draft_id}';
};

export type EditDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditDraftError = EditDraftErrors[keyof EditDraftErrors];

export type EditDraftResponses = {
    /**
     * Successful Response
     */
    200: DraftPublic;
};

export type EditDraftResponse = EditDraftResponses[keyof EditDraftResponses];

export type GenerateDraftData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/drafts/{draft_id}/generate';
};

export type GenerateDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateDraftError = GenerateDraftErrors[keyof GenerateDraftErrors];

export type GenerateDraftResponses = {
    /**
     * Successful Response
     */
    200: DraftPublic;
};

export type GenerateDraftResponse = GenerateDraftResponses[keyof GenerateDraftResponses];

export type PublishDraftData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/drafts/{draft_id}/publish';
};

export type PublishDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishDraftError = PublishDraftErrors[keyof PublishDraftErrors];

export type PublishDraftResponses = {
    /**
     * Successful Response
     */
    201: PostPublic;
};

export type PublishDraftResponse = PublishDraftResponses[keyof PublishDraftResponses];

export type ListPostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/posts';
};

export type ListPostsResponses = {
    /**
     * Response List Posts
     *
     * Successful Response
     */
    200: Array<PostSummary>;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type GetPostData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/posts/{slug}';
};

export type GetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
    /**
     * Successful Response
     */
    200: PostPublic;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type StreamRevisionData = {
    body: RevisionRequest;
    path?: never;
    query?: never;
    url: '/api/revisions/stream';
};

export type StreamRevisionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamRevisionError = StreamRevisionErrors[keyof StreamRevisionErrors];

export type StreamRevisionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
